### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by sunscreem** [riasvdv/statamic-color-swatches#18]
Just trying out this add-on and its generating duplicate items which I can't remove.

![image](https://user-images.githubusercontent.com/7523595/118320690-7dc4c700-b4f4-11eb-900c-c3bc66b44378.png)

**Comment by riasvdv** [comment]
Until #7 is fixed, I suggest only managing the colors using the yaml file. The grid field doesn't work well in the blueprint editor currently.
