### ISSUE TITLE
Ability to add class name, rather than just colour value

### ISSUE THREAD

**Issue by Hicksdesign** [riasvdv/statamic-color-swatches#2]
For more complex use cases, it would be great if there was an option to show colour swatches the CP, but add them as a class name in the template. For example, a white on black colour scheme on a particular content block that contains various elements like SVG icons. If a class name could be output in the template, it would allow control over all of those child elements.

**Comment by riasvdv** [comment]
You can use `{{ yourColorField.label }}` and set the label of the configured color as the class you want

**Comment by Hicksdesign** [comment]
Excellent, thankyou!
