### ISSUE TITLE
Statamic spits out a debug error on each save

### ISSUE THREAD

**Issue by robdekort** [riasvdv/statamic-color-swatches#4]
dev.DEBUG: Invalid route action: [Statamic\Addons\ColorSwatches\ColorSwatchesController]

**Comment by riasvdv** [comment]
Hmm there's nothing in my code that points to a controller, are you on the latest version? Maybe try `php please addons:refresh`, that might solve it

**Comment by robdekort** [comment]
Yes latest version (1.0). Refreshing / updating doesn't help. What does seem to help is emptying routes.yaml. Everything seems to work fine after. I don't know what the file does :-). You probably know better.

**Comment by riasvdv** [comment]
Ah, that's from when I generated the boilerplate. I've deleted it in 1.0.3!

**Comment by robdekort** [comment]
Cool!

**Comment by robdekort** [comment]
Works! Now maybe update the version number in meta.yaml ;-)
