### ISSUE TITLE
Receiving error when trying to add color swatch.

### ISSUE THREAD

**Issue by danpaquette** [riasvdv/statamic-color-swatches#7]
Fresh install, Statamic v3.0.0-beta.27.

https://imgur.com/a/nJRnZAa

I am receiving this error in both blueprints and fieldsets. Let me know if there's any further information I can provide.

Thanks!

**Comment by danpaquette** [comment]
I'm also receiving this error on your Button Box addon as well. https://github.com/riasvdv/statamic-button-box

I can create a separate issue there if you prefer.

**Comment by riasvdv** [comment]
Yes, unfortunately this is an issue with the Statamic beta: https://github.com/statamic/cms/issues/1616

Once this is fixed the field settings will work properly, until then they work perfectly if you define the config in the yml file

**Comment by riasvdv** [comment]
Finally fixed in core :)
